### ISSUE TITLE
3.4.2 and 3.4.3 are not showing up on packagist

### ISSUE THREAD

**Issue by garethellis36** [jobbyphp/jobby#105]
Latest version is still 3.4.1. 
https://packagist.org/packages/hellogerard/jobby

**Comment by garethellis36** [comment]
Looks like some action is needed on Packagist?

https://twitter.com/packagist/status/1037035587453235201

> If you have published packages from GitHub on http://packagist.org  please logout/login with GitHub to let us upgrade the auto-update hooks and remove the deprecated GitHub service hooks.

**Comment by hellogerard** [comment]
It's updated now. Yeah, they changed the Github hooks. I manually updated, and also installed the new Github hooks. Thanks!

**Comment by garethellis36** [comment]
That was fast, thanks!
