### ISSUE TITLE
DateTimeImmutable and PHP Version

### ISSUE THREAD

**Issue by christos1984** [jobbyphp/jobby#106]
After installing latest version of Jobby on a machine with PHP 5.4.16 Jobby can't execute because of DateTimeImmutable in line 158 in Jobby.php file.

`PHP Fatal error:  Class 'DateTimeImmutable' not found`

DateTimeImmutable is present after >= 5.5 and the composer.json of Jobby lists 5.4 as the minimum working version.

**Comment by hellogerard** [comment]
Sorry, forgot to bump the minimum version. PHP 5.4 and 5.4 are EOL, so the minimum version for this package is 5.6.
