### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by darkalchemy** [jobbyphp/jobby#124]
Has this project been abandoned?

If you are open to it, I would like to join and help with keeping it current. I use this project and don't want to see it abandoned.

Thanks

PS
At least, I would to try - I am still learning.

**Comment by hellogerard** [comment]
It is basically abandoned, as I do not use PHP anymore. I only merge PRs. However, I set up the Github org in order to accommodate new maintainers. If you're interested, I can add you to the org.

**Comment by darkalchemy** [comment]
I would like that. 
Thanks
