### ISSUE TITLE
Updating 2.2.0 to 3.x.x

### ISSUE THREAD

**Issue by dyelton** [jobbyphp/jobby#51]
I'm running into the following issue updating to either 3.0.0 or 3.0.1:

> Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

 > Problem 1
    - Can only install one of: jeremeamia/SuperClosure[2.2.0, 2.1.0].
    - Can only install one of: jeremeamia/SuperClosure[2.2.0, 2.1.0].
    - Can only install one of: jeremeamia/SuperClosure[2.2.0, 2.1.0].
    - hellogerard/jobby v3.0.1 requires jeremeamia/superclosure ^2.2 -> satisfiable by jeremeamia/SuperClosure[2.2.0].
    - Installation request for hellogerard/jobby v3.0.1 -> satisfiable by hellogerard/jobby[v3.0.1].
    - Installation request for jeremeamia/superclosure == 2.1.0.0 -> satisfiable by jeremeamia/SuperClosure[2.1.0].

**Comment by hellogerard** [comment]
Did you try running `composer dump`?

**Comment by dyelton** [comment]
@hellogerard I ran it but it didn't help. Updating other packages in my project doesn't have the issue, just isolated to this one unfortunately.

**Comment by xabbuh** [comment]
@dyelton Can you show your complete `composer.json` file?

**Comment by dyelton** [comment]
> {
  "name": "carpenter/orion",
  "description": "something awesome",
  "minimum-stability": "stable",
  "license": "proprietary",
  "authors": [
    {
      "name": "Me",
      "email": "dyelton@awesomeproject.com"
    }
  ],
  "require": {
    "twig/twig": "v1.24.0",
    "mobiledetect/mobiledetectlib": "2.8.19",
    "phpmailer/phpmailer": "v5.2.14",
    "league/csv": "8.0.0",
    "hellogerard/jobby": "v3.0.1",
    "codeguy/upload": "1.3.2",
    "slim/twig-view": "2.1.1",
    "monolog/monolog": "1.18.1",
    "slim/flash": "0.1.0",
    "slim/slim": "3.3.0",
    "cartalyst/converter": "v2.0.3",
    "slim/http-cache": "0.3.0"
  }
}

**Comment by xabbuh** [comment]
I cannot reproduce your issue. Using that `composer.json` file running `composer install` ends up with these packages being installed:

```
cartalyst/converter                 v2.0.3  A framework agnostic measurement conversion and formatting package featuring multiple types of measurements and currency conversion.
codeguy/upload                      1.3.2   Handle file uploads with extensible validation and storage strategies
container-interop/container-interop 1.1.0   Promoting the interoperability of container objects (DIC, SL, etc.)
doctrine/inflector                  v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
guzzlehttp/guzzle                   5.3.0   Guzzle is a PHP HTTP client library and framework for building RESTful web service clients
guzzlehttp/ringphp                  1.1.0   Provides a simple API and specification that abstracts away the details of HTTP into a single PHP function.
guzzlehttp/streams                  3.0.0   Provides a simple abstraction over streams of data
hellogerard/jobby                   v3.0.1  Manage all your cron jobs without modifying crontab. Handles locking, logging, error emails, and more.
illuminate/cache                    v5.2.21 The Illuminate Cache package.
illuminate/contracts                v5.2.21 The Illuminate Contracts package.
illuminate/filesystem               v5.2.21 The Illuminate Filesystem package.
illuminate/support                  v5.2.21 The Illuminate Support package.
jeremeamia/SuperClosure             2.2.0   Serialize Closure objects, including their context and binding
league/csv                          8.0.0   Csv data manipulation made easy in PHP
mobiledetect/mobiledetectlib        2.8.19  Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-Agent string combined with specific HTTP hea...
monolog/monolog                     1.18.1  Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression           v1.1.0  CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
nesbot/carbon                       1.21.0  A simple API extension for DateTime.
nikic/fast-route                    v0.6.0  Fast request router for PHP
nikic/php-parser                    v2.0.1  A PHP parser written in PHP
phpmailer/phpmailer                 v5.2.14 PHPMailer is a full-featured email creation and transfer class for PHP
pimple/pimple                       v3.0.2  Pimple, a simple Dependency Injection Container
psr/http-message                    1.0     Common interface for HTTP messages
psr/log                             1.0.0   Common interface for logging libraries
react/promise                       v2.2.2  A lightweight implementation of CommonJS Promises/A for PHP
slim/flash                          0.1.0   Slim Framework Flash message service provider
slim/http-cache                     0.3.0   Slim Framework HTTP cache middleware and service provider
slim/slim                           3.3.0   Slim is a PHP micro framework that helps you quickly write simple yet powerful web applications and APIs
slim/twig-view                      2.1.1   Slim Framework 3 view helper built on top of the Twig templating component
swiftmailer/swiftmailer             v5.4.1  Swiftmailer, free feature-rich PHP mailer
symfony/finder                      v3.0.3  Symfony Finder Component
symfony/polyfill-mbstring           v1.1.1  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56              v1.1.1  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util               v1.1.1  Symfony utilities for portability of PHP codes
symfony/process                     v3.0.3  Symfony Process Component
symfony/translation                 v3.0.3  Symfony Translation Component
twig/twig                           v1.24.0 Twig, the flexible, fast, and secure template language for PHP
```

**Comment by dyelton** [comment]
Note that I currently have Jobby 2.2.0 installed and I'm trying to upgrade to 3.0.0 or 3.0.1. That's when I get the error.

**Comment by xabbuh** [comment]
What steps do you perform to make the update?

**Comment by dyelton** [comment]
@xabbuh What happens if you do a composer install for my json file but use Jobby v2.2.0 and then just change it's version to v3.0.1 and do an update on Jobby?

I use PHPStorm and just running the c update hellogerard/jobby command (c is a pointer to composer in my case).

**Comment by xabbuh** [comment]
@dyelton Use the `--with-dependencies` option to solve your issue:

```bash
$ composer update hellogerard/jobby --with-dependencies
```

**Comment by dyelton** [comment]
@xabbuh Thanks, that got things rolling again!
