### ISSUE TITLE
Jobby doesn't follow schedule parameter

### ISSUE THREAD

**Issue by florianbepunkt** [jobbyphp/jobby#57]
I set up Jobby as described and added a corresponding entry to my crontab.

However: The schedule I set gets disregarded and all jobs run everytime Jobby is run.

If I set Jobby in chrontab to run every minute and a job in jobb to run every ten minutes, it runs every minute. If i set Jobby to run only every five minutes, the job runs every five minutes.

Any idea why it doesn't take the schedule parameter into account?

Thanks,
Florian

**Comment by florianbepunkt** [comment]
Okay, when I try to access the jobby.php directly on my server, the line

`$jobby->run();`

throws a 500 internal server error. No idea why :/

**Comment by florianbepunkt** [comment]
bump

**Comment by hellogerard** [comment]
Can't seem to reproduce this. You say you had to add posix?  Are you on Windows?
