### ISSUE TITLE
How does Jobby handle overlapping jobs?

### ISSUE THREAD

**Issue by xfactor5** [jobbyphp/jobby#66]
Hi,
Suppose I have a mailer that sends emails every minute, for one minute the number of emails in the queue is high and somehow the process will last 65 seconds, now after 60 seconds the job is re-run again, and it might pick some stuff from the queue while they are being processed by the previous job.
Is it programmers duty to handle this with some sort of lock or Jobby can handle that somehow?
This library [php-cron-scheduler](https://github.com/peppeocchi/php-cron-scheduler) seems to have some sort of temp folder and checking mechanism for this, which I didn't find in the readme file of Jobby.
Thanks

**Comment by hellogerard** [comment]
Jobby does support this scenario. It's listed in the features:

```
Run only one copy of a job at a given time
```

It uses POSIX file semantics to do so. You can see it in the code. If you find that this isn't working as expected, feel free to open a bug. Cheers!
