### ISSUE TITLE
How does it deal with missed Jobs

### ISSUE THREAD

**Issue by zainengineer** [jobbyphp/jobby#67]
How does it track missed jobs?
For example if cron is scheduled to run at exact 2 AM every night
but jobby misses it because it is running other jobs, will it run 2 AM job?

How it deals with missed jobs in general?

Thanks

**Comment by hellogerard** [comment]
Jobby runs jobs concurrently, so it doesn't matter if multiple jobs are scheduled to run at once.

As long as your main cron job is setup right, jobs should always get a chance to run. The main cron job is purposefully light on logic, to reduce chance of errors, but if the main cron job wasn't firing jobs on schedule, that would be a bug.
