### ISSUE TITLE
How does Joby handle multi process that take more then 10 minutes to each?

### ISSUE THREAD

**Issue by rhayun** [jobbyphp/jobby#70]
Hello

i have 3 process that should run every minute
i believe Jobby run each process is synchrony way. so it will run process number 1 and then when it will check schedule for the next process the schedule will not match because process 1 take long time..  am i wrong? (sorry about my english)

**Comment by hellogerard** [comment]
No, that doesn't sound right. Jobby forks new processes for each job, so the only thing it's really doing every minute is checking schedules. I could see if you had 1000+ jobs then just cron scheduling could exceed a minute, but that's super unlikely. Can you reproduce this reliably?
