### ISSUE TITLE
Force PHP version

### ISSUE THREAD

**Issue by kojoduncan** [jobbyphp/jobby#75]
Hello,

Is there a way to override the php version that jobby uses to run cron jobs. I have a script which runs fine on my webserver which uses PHP 5.6 but when I run the same php script in cron it gives errors related to the php version. I run a phpinfo() as a php script in crontab and got php version 5.4.45.

Can jobby be configured to use a different php version?

Thanks

**Comment by hellogerard** [comment]
@kojoduncan I think it just uses the php installed in your shell. If you just type `php -v` at the prompt, it is probably 5.4.45. If you type `which php`, it will tell you where it is is installed. Upgrade your command-line php if you want a newer version.

**Comment by kojoduncan** [comment]
Thanks. That worked.
