### ISSUE TITLE
hello,how can i  integration with CodeIgniter

### ISSUE THREAD

**Issue by allenfinddream** [jobbyphp/jobby#82]
$task['task_sync_order']['closure'] = function (){
           $this->load->model('model_name');
            return true;
        };
while i am doing this ,it do nothing, how can i solve this problem,thanks

**Comment by chengxueming** [comment]
i also want to ask this, i am seeking a tool which can be used in mis. i want to add or remove job which execute at specific time and control it via user interface .We also use codeigniter. i want to know jobby is a good choice or not.
