### ISSUE TITLE
how to execute function in Closure 

### ISSUE THREAD

**Issue by sansanboy** [jobbyphp/jobby#93]
> <?php

//
// Add this line to your crontab file:
//
// * * * * * cd /path/to/project && php jobby.php 1>> /dev/null 2>&1
//

require_once __DIR__ . '/vendor/autoload.php';

//require_once 'TestCs.php';

try {

    class TestCs {
        public function test($a) {
            echo $a;
        }
    }
    $jobby = new \Jobby\Jobby();
    $t = new TestCs();
    $jobby->add('ClosureCommandExample', [
        'closure'  => function()   use ( $t){
            echo "I'm a function!\n";
            $t->test("adasd");
            return true;
        },
        'schedule' => '* * * * *',
        'output' => 'logs/my.log',
        'enabled' => true,
    ]);

    $jobby->run();

} catch (Exception $e) {
    var_dump($e);
}

I want to execute test, but do not work.

**Comment by liwei1991** [comment]
I have the same problem， have you solved it

**Comment by SFlame** [comment]
Same problem here.. has anyone managed to solve the problem?

**Comment by hellogerard** [comment]
Thanks for the solution. Added a note to the doc.
