### ISSUE TITLE
Is the ENABLED flag being honored?

### ISSUE THREAD

**Issue by Cure4Life** [jobbyphp/jobby#98]
I have some jobs that have ENABLED=0 and the jobs are still being ran. Checking the code, I don't see where the ENABLED parameter is being checked before execution. Since our jobs are read from a MySQL database, I can easily filter out any with ENABLED=0 but I just wanted to confirm if this was an issue or if I was missing something here.

Thanks

**Comment by hellogerard** [comment]
No, it should work. The line is here: https://github.com/jobbyphp/jobby/blob/44694c18b2d5568bf84722c353e2fdec4a4368b2/src/BackgroundJob.php#L199. If it's not, then this is a bug.

**Comment by Cure4Life** [comment]
Hi. Thanks for replying. I was just following the code from when i issue $jobby->run(); Based on the example in jobby-pdo.php. 

I don't see where it calls shouldRun() or does any $config['enabled'] check. Should I be using a different class other than $jobby = new \Jobby\Jobby(); ?

\Jobby\Jobby::run() defers to \Jobby\Jobby::runUnix(). I cannot find where this parameters is checked in any of that.

Thanks again!

**Comment by fjeddy** [comment]
Works fine on this end, try

`'enabled' => false` instead of `'ENABLED' => false`

**Comment by Cure4Life** [comment]
I was capitalizing as a way of focusing on the issue, not literally in the code. Consider the following example from the jobby-pdo.php example file:


$jobbiesStmt = $dbh->query("SELECT * FROM `$dbhJobbiesTableName`");
$jobbies = $jobbiesStmt->fetchAll(PDO::FETCH_ASSOC);
$jobby = new \Jobby\Jobby();
foreach ($jobbies as $job) {
    // Filter out each value, which is not set (for example, "maxRuntime" is not defined in the job).
    $job = array_filter($job);
    try {
        $job['closure'] = $serializer->unserialize($job['command']);
        unset($job['command']);
    } catch (SuperClosure\Exception\ClosureUnserializationException $e) {
    }
    $jobName = $job['name'];
    unset($job['name']);
    $jobby->add($jobName, $job);
}
$jobby->run();


I had to change the select to:

$jobbiesStmt = $dbh->query("SELECT * FROM `$dbhJobbiesTableName` WHERE `enabled` = 1");

in order to keep disabled tasks from running, as it would seem that the enabled flag was not being checked properly elsewhere.
